import time
from select import select
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import keys
driver=webdriver.Firefox(executable_path="F:\Selenium\geckodriver")
driver.get("http://192.168.1.105:8060/web/database/selector")
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/a[4]").click()
time.sleep(2)
element=driver.find_element_by_id("login").send_keys("nurnabi@scclbd.com")
element=driver.find_element_by_id("password").send_keys("@dminsccl")
time.sleep(4)
driver.find_element_by_xpath("/html/body/div/main/div/form/div[4]/button").click()
time.sleep(6)
driver.find_element_by_xpath("/html/body/nav/div[2]/ul[1]/li[7]/a/span").click()
time.sleep(6)
driver.find_element_by_xpath("/html/body/div[1]/div[1]/div[1]/div[7]/ul[1]/li[4]/a/span").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div[1]/div/div[3]/table[1]/tbody/tr[7]/td[2]/div/div").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/ul[2]/li[4]/a").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div[1]/div/div[3]/table[1]/tbody/tr[8]/td[2]/div/div").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/ul[3]/li[4]/a").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div[1]/div/div[3]/table[1]/tbody/tr[12]/td[2]/div/div").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/ul[4]/li[5]/a").click()
time.sleep(2)
element=driver.find_element_by_id("o_field_input_19").send_keys("Gulshan")
time.sleep(2)
driver.find_element_by_id("o_field_input_27").clear()
element=driver.find_element_by_css_selector("#o_field_input_27").send_keys(50000)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div[1]/div/div[3]/table[2]/tbody/tr[2]/td[2]/div/div/div").click()
driver.find_element_by_xpath("/html/body/ul[7]/li[1]/a").click()
# SO select
element=driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div[1]/div/div[3]/table[2]/tbody/tr[3]/td[2]/textarea[1]").send_keys("test")
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/header/button[3]/span").click()