import time
from select import select
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import keys
driver=webdriver.Firefox(executable_path="F:\Selenium\geckodriver")
driver.get("http://192.168.1.105:8060/web/database/selector")
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/a[4]").click()
time.sleep(2)
element=driver.find_element_by_id("login").send_keys("rafsansheikh@yahoo.com")
element=driver.find_element_by_id("password").send_keys("@dminsccl")
time.sleep(2)
driver.find_element_by_xpath("/html/body/div/main/div/form/div[4]/button").click()
time.sleep(5)
driver.find_element_by_xpath("/html/body/nav/div[2]/ul[1]/li[3]/a/span").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div[1]/div[1]/div[3]/ul[1]/li[3]/a/span").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element_by_id("o_field_input_11").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/ul[4]/li[4]/a").click()
time.sleep(2)
#Customer select
driver.find_element_by_id("o_field_input_7").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/ul[2]/li[7]/a").click()
time.sleep(2)
driver.find_element_by_id("o_field_input_8").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/ul[3]/li[1]/a").click()
time.sleep(2)
driver.find_element_by_id("o_field_input_13").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/ul[5]/li[6]/a").click()
time.sleep(5)
driver.find_element_by_id("o_field_input_14").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/ul[6]/li[4]/a").click()
time.sleep(5)
# Type select
driver.find_element_by_id("o_field_input_15").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/ul[7]/li[3]/a").click()
time.sleep(2)
# Operating unit select
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div[1]/div/div/div/div/div[1]/div/div[2]/div[2]/table/tbody/tr[1]/td/a").click()
time.sleep(3)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div[1]/div/div/div/div/div[1]/div/div[2]/div[1]/div[1]/div/input").click()
time.sleep(3)
driver.find_element_by_xpath("/html/body/ul[8]/li[1]/a").click()
time.sleep(3)
#driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div[1]/div/div[4]/div/div[1]/div[1]/div[2]/div[1]/input[1]").click()
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div[1]/div/div/div/div/div[1]/div/div[2]/div[1]/input[1]").clear()
driver.find_element_by_css_selector("input.o_form_input:nth-child(3)").send_keys("100")
time.sleep(3)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div[1]/div/div/div/div/div[1]/div/div[2]/div[2]/table/tbody/tr[1]/td[5]").click()
time.sleep(3)
driver.find_element_by_css_selector("input.o_form_input:nth-child(5)").clear()
#time.sleep(3)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div[1]/div/div/div/div/div[1]/div/div[2]/div[1]/input[2]").send_keys("300")
time.sleep(3)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/header/button[1]/span").click()