import time
from select import select
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import keys
driver=webdriver.Firefox(executable_path="F:\Selenium\geckodriver")
driver.get("http://192.168.1.105:8060/web/database/selector")
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/a[4]").click()
time.sleep(2)
element=driver.find_element_by_id("login").send_keys("rafsansheikh@yahoo.com")
element=driver.find_element_by_id("password").send_keys("@dminsccl")
time.sleep(2)
driver.find_element_by_xpath("/html/body/div/main/div/form/div[4]/button").click()
time.sleep(5)
driver.find_element_by_xpath("/html/body/nav/div[2]/ul[1]/li[3]/a/span").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div[1]/div[1]/div[3]/ul[1]/li[2]/a/span").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element_by_id("o_field_input_17").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/ul[4]/li[8]/a").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[7]/div/div/div[2]/div[2]/div/table/tbody/tr[8]/td[2]").click()
time.sleep(7)
driver.find_element_by_id("o_field_input_22").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/ul[7]/li[1]/a").click()
time.sleep(2)
# PI Select
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/header/button[14]/span").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/nav/div[2]/ul[2]/li/a/span[2]").click()
driver.find_element_by_xpath("/html/body/nav/div[2]/ul[2]/li/ul/li[3]/a").click()
time.sleep(2)
#logout
element=driver.find_element_by_id("login").send_keys("rony@scclbd.com")
element=driver.find_element_by_id("password").send_keys("@dminsccl")
time.sleep(2)
# Sales approval
driver.find_element_by_xpath("/html/body/div/main/div/form/div[4]/button").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/nav/div[2]/ul[1]/li[3]/a/span").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div[1]/div[1]/div[3]/ul[1]/li[1]/a").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div/table/tbody/tr[1]/td[2]").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/header/button[15]").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/nav/div[2]/ul[2]/li/a/span[2]").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/nav/div[2]/ul[2]/li/ul/li[3]/a").click()
time.sleep(2)
#logout
element=driver.find_element_by_id("login").send_keys("ma.zaman@scclbd.com")
element=driver.find_element_by_id("password").send_keys("@dminsccl")
time.sleep(2)
driver.find_element_by_xpath("/html/body/div/main/div/form/div[4]/button").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/nav/div[2]/ul[1]/li[3]/a/span").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div[1]/div[1]/div[3]/ul[1]/li[1]/a/span").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div/table/tbody/tr[1]/td[2]").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/header/button[16]/span").click()
# Accounts approval
driver.find_element_by_xpath("/html/body/nav/div[2]/ul[2]/li/a/span[2]").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/nav/div[2]/ul[2]/li/ul/li[3]/a").click()
#logout
time.sleep(2)
element=driver.find_element_by_id("login").send_keys("das.bk.sccl@gmail.com")
element=driver.find_element_by_id("password").send_keys("@dminsccl")
time.sleep(2)
driver.find_element_by_xpath("/html/body/div/main/div/form/div[4]/button").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/nav/div[2]/ul[1]/li[3]/a/span").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div[1]/div[1]/div[3]/ul[1]/li[1]/a/span").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div/table/tbody/tr[1]/td[2]").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/header/button[5]/span").click()
# CXO approval