import time

import selenium
from select import select
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import keys
from selenium.webdriver.common.keys import keys
driver=webdriver.Firefox(executable_path="E:\Selenium\geckodriver")
driver.get("https://gen-bizbd.com/web/login")
time.sleep(2)
driver.find_element("id", "login").send_keys("wahid@scclbd.com")
driver.find_element("id", "password").send_keys("&dminERPSamuda")
time.sleep(2)
driver.find_element("xpath", "/html/body/div/main/div/form/div[3]/button").click()
time.sleep(7)
driver.find_element("xpath", "/html/body/nav/div[2]/ul[1]/li[3]/a/span").click()
time.sleep(4)
driver.find_element("xpath", "/html/body/div[1]/div[1]/div[1]/div[3]/ul[2]/li[5]/a/span").click()
time.sleep(4)
driver.find_element("xpath", "/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(4)
driver.find_element("xpath", "/html/body/div[1]/div[1]/div[1]/div[3]/ul[2]/li[3]/a/span").click()
time.sleep(6)
driver.find_element("xpath", "/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath", "/html/body/div[1]/div[1]/div[1]/div[3]/ul[2]/li[4]/a/span").click()
time.sleep(4)
driver.find_element("xpath", "/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath", "/html/body/div[1]/div[1]/div[1]/div[3]/ul[3]/li[1]/a/span").click()
time.sleep(6)
driver.find_element("xpath", "/html/body/div[1]/div[2]/div[2]/div/div/div[4]/div[3]").click()
time.sleep(4)
driver.find_element("xpath", "/html/body/div[1]/div[1]/div[1]/div[3]/ul[3]/li[2]/a/span").click()
time.sleep(4)
driver.find_element("xpath", "/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath", "/html/body/div[1]/div[1]/div[1]/div[3]/ul[3]/li[3]/a").click()
time.sleep(4)
driver.find_element("xpath", "/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath", "/html/body/div[1]/div[1]/div[1]/div[3]/ul[4]/li[1]/a").click()
time.sleep(4)
driver.find_element("xpath", "/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button").click()
time.sleep(2)
driver.find_element("xpath", "/html/body/div[1]/div[1]/div[1]/div[3]/ul[4]/li[2]/a/span").click()
time.sleep(4)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[3]/ul[5]/li[1]/a/span").click()
time.sleep(4)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[2]/div/div/div/table/tbody/tr[1]/td[2]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/nav/div[2]/ul[1]/li[4]/a/span").click()
time.sleep(4)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[4]/ul[5]/li[1]/a/span").click()
time.sleep(4)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[4]/ul[5]/li[2]/a/span").click()
time.sleep(4)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[4]/ul[5]/li[3]/a/span").click()
time.sleep(4)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[4]/ul[5]/li[4]/a/span").click()
time.sleep(4)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[4]/ul[9]/li[2]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[4]/ul[9]/li[3]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[4]/ul[9]/li[4]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[4]/ul[9]/li[7]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[4]/ul[9]/li[8]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[4]/ul[9]/li[9]/a").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[4]/ul[9]/li[10]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[4]/ul[9]/li[11]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[4]/ul[9]/li[12]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/nav/div[2]/ul[1]/li[5]/a/span").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[5]/ul[2]/li[1]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[5]/ul[3]/li[1]/a").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[5]/ul[4]/li[2]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/nav/div[2]/ul[1]/li[7]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[7]/ul[1]/li[2]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/nav/div[2]/ul[1]/li[8]/a/span").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[8]/ul[1]/li[1]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[2]/div/div/div/table/tbody/tr[1]/td[2]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[8]/ul[1]/li[3]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[8]/ul[1]/li[4]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[8]/ul[1]/li[5]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[8]/ul[1]/li[7]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[8]/ul[1]/li[7]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[8]/ul[2]/li[1]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[8]/ul[2]/li[3]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[8]/ul[2]/li[5]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[8]/ul[4]/li[2]/a").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[8]/ul[4]/li[3]/a/span").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.find_element("xpath","/html/body/div[1]/div[1]/div[1]/div[8]/ul[4]/li[6]/a").click()
time.sleep(6)
driver.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(2)
driver.close()