import time
from select import select
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import keys
from selenium.webdriver.common.keys import keys
driver=webdriver.Firefox(executable_path="F:\Selenium\geckodriver")
driver.get("https://gen-bizbd.com/web/login")
time.sleep(2)
element=driver.find_element_by_id("login").send_keys("rony@scclbd.com")
element=driver.find_element_by_id("password").send_keys("asdasf")
time.sleep(2)
driver.find_element_by_xpath("/html/body/div/main/div/form/div[3]/button").click()
time.sleep(7)
driver.find_element_by_xpath("/html/body/nav/div[2]/ul[1]/li[3]/a/span").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[1]/div[1]/div[3]/ul[1]/li[1]/a/span").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[1]/div[1]/div/div/div[2]").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div/table/tbody/tr[1]/td[2]").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[1]/div[1]/div[3]/ul[1]/li[2]/a/span").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[1]/div[1]/div/div/div[2]").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div/table/tbody/tr[1]/td[2]").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[1]/div[1]/div[3]/ul[1]/li[3]/a/span").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[1]/div[1]/div/div/div[2]").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div/table/tbody/tr[1]/td[2]").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[1]/div[1]/div[3]/ul[1]/li[4]/a/span").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[1]/div[1]/div/div/div[2]").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div/table/tbody/tr[1]/td[2]").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[1]/div[1]/div[3]/ul[4]/li[4]/a/span").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div/div/table/tbody/tr[1]/td[2]").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/nav/div[2]/ul[1]/li[4]/a/span").click()
time.sleep(4)
driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[1]/div[2]/div[1]/div/button[1]").click()
time.sleep(4)
driver.close()